### ISSUE TITLE
DB 返回数据类型错误

### ISSUE THREAD

**Issue by mohuishou** [uTools-Labs/utools-api-types#1]
https://github.com/uTools-Labs/utools-api-types/blob/3d3bef324b1a665df34d4d9834e340bc0285ae7c/utools.api.d.ts#L557

这么返回的话，在 ts 中无法添加其他数据

**Comment by uTools-Labs** [comment]
> https://github.com/uTools-Labs/utools-api-types/blob/3d3bef324b1a665df34d4d9834e340bc0285ae7c/utools.api.d.ts#L557
> 
> 这么返回的话，在 ts 中无法添加其他数据

没明白你意思，是指声明问题还是本身 API 问题？

**Comment by mohuishou** [comment]
声明的问题，这么声明写 ts 得做一下类型转换
```
 let itemOld = utools.db.get("config");
 let data = itemOld as { _id: string; _rev: string; data: any };
```
因为除了 ` { _id: string, _rev: string } ` 两个字段，我还保存了 data 字段

**Comment by uTools-Labs** [comment]
> 声明的问题，这么声明写 ts 得做一下类型转换
> 
> ```
>  let itemOld = utools.db.get("config");
>  let data = itemOld as { _id: string; _rev: string; data: any };
> ```
> 
> 因为除了 `{ _id: string, _rev: string }` 两个字段，我还保存了 data 字段

已优化
